-- Geração de Modelo físico


    
CREATE TABLE PESSOA
(
ID_PESSOA SERIAL PRIMARY KEY,
NOME varchar(5), 
CPF varchar(11),
TELEFONE varchar(15),
EMAIL varchar(50),
DATA_DE_NASCIMENTO Date, 
NACIONALIDADE varchar(50), 
);


CREATE TABLE PESSOA_PASSAGEIRO 
(
ID_PASSAGEIRO SERIAL PRIMARY KEY,
ID_PESSOA SERIAL,
ID_PASSAGEM SERIAL
);


CREATE TABLE PESSOA_FUNCIONARIO
(
ID_FUNCIONARIO SERIAL PRIMARY KEY,
ID_PESSOA SERIAL,
ID_EMPRESA SERIAL
);


CREATE TABLE EMPRESAS
(
ID_EMPRESA PRIMARY KEY,
NOME varchar(50), 
CLASSIFICACAO SERIAL
);


CREATE TABLE EMPRESA_COMPANHIA
(
ID_COMPANHIA PRIMARY KEY,
CLASSIFICACAO SERIAL
TELEFONE varchar(9),
EMAIL varchar(50)
);


CREATE TABLE EMPRESA_RODOVIARIA
(
ID_RODOVIARIA SERIAL PRIMARY KEY, 
CLASSIFICACAO SERIAL
ENDERECO varchar(10), 
HORARIO_DE_FUNCIONAMENTO Time
);



CREATE TABLE ROTAS
( 
ID_ROTA SERIAL PRIMARY KEY,
ID_COMPANHIA SERIAL, 
DESTINO varchar(50), 
HORA_SAIDA Time,
HORA_CHEGADA Time,
);


CREATE TABLE PASSAGEM
( 
ID_PASSAGEM SERIAL PRIMARY KEY, 
ID_ROTA SERIAL,
DATA_COMPRA Timestamp,
DATA_VIAGEM Timestamp,
PRECO Money
);




ALTER TABLE EMPRESAS ADD FOREIGN KEY(CLASSIFICACAO) REFERENCES EMPRESA_RODOVIARIA (CLASSIFICACAO);
ALTER TABLE EMPRESAS ADD FOREIGN KEY(CLASSIFICACAO) REFERENCES EMPRESA_COMPANHIA (CLASSIFICACAO);

ALTER TABLE ROTAS ADD FOREIGN KEY(ID_COMPANHIA) REFERENCES EMPRESA_COMPANHIA (ID_COMPANHIA);

ALTER TABLE PASSAGEM ADD FOREIGN KEY(ID_ROTA) REFERENCES ROTAS (ID_ROTA);

ALTER TABLE PESSOA_PASSAGEIRO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA (ID_PESSOA);
ALTER TABLE PESSOA_PASSAGEIRO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PASSAGEM (ID_PASSAGEM);

ALTER TABLE PESSOA_FUNCIONARIO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA (ID_PESSOA);
ALTER TABLE PESSOA_FUNCIONARIO ADD FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA);

