-- Geração de Modelo físico



/* Lógico_3: */

CREATE TABLE Rotas (
    Hora_chegada VARCHAR[30],
    ID_rota INTEGER PRIMARY KEY,
    Hora_saida VARCHAR[30],
    ID_rodoviaria_saida INTEGER,
    ID_rodoviaria_chegada INTEGER
);

CREATE TABLE Empresa (
    Nome VARCHAR[30],
    ID_empresa INTEGER PRIMARY KEY,
    Telefone VARCHAR[30]
);

CREATE TABLE Pessoa (
    Nome VARCHAR[30],
    Identidade VARCHAR[30],
    CPF VARCHAR[30],
    Nacionalidade VARCHAR[30],
    ID_pessoa INTEGER PRIMARY KEY,
    Telefone VARCHAR[30],
    Email VARCHAR[30],
    Data_de_nascimento DATE
);

CREATE TABLE Pessoa_passageiro (
    ID_passageiro INTEGER,
    ID_pessoa INTEGER,
    ID_passagem INTEGER,
    FK_Pessoa_ID_pessoa INTEGER,
    PRIMARY KEY (ID_passageiro, FK_Pessoa_ID_pessoa)
);

CREATE TABLE Pessoa_funcionario (
    ID_funcionario INTEGER,
    ID_pessoa INTEGER,
    ID_empresa INTEGER,
    FK_Pessoa_ID_pessoa INTEGER,
    PRIMARY KEY (ID_funcionario, FK_Pessoa_ID_pessoa)
);

CREATE TABLE Passagem (
    ID_passagem INTEGER PRIMARY KEY,
    ID_rota INTEGER,
    ID_companhia INTEGER,
    Data_compra VARCHAR[30],
    Data_viagem VARCHAR[30],
    preco DOUBLE
);

CREATE TABLE Companhia (
    ID_companhia INTEGER,
    ID_empresa INTEGER,
    email VARCHAR[30],
    FK_Empresa_ID_empresa INTEGER,
    PRIMARY KEY (ID_companhia, FK_Empresa_ID_empresa)
);

CREATE TABLE Rodoviaria (
    Horario_de_funcionamento VARCHAR[30],
    ID_rodoviaria INTEGER,
    FK_Empresa_ID_empresa INTEGER,
    PRIMARY KEY (ID_rodoviaria, FK_Empresa_ID_empresa)
);

CREATE TABLE Tem (
    FK_Pessoa_passageiro_ID_passageiro INTEGER,
    FK_Pessoa_passageiro_FK_Pessoa_ID_pessoa INTEGER,
    FK_Passagem_ID_passagem INTEGER
);
 
ALTER TABLE Pessoa_passageiro ADD CONSTRAINT FK_Pessoa_passageiro_1
    FOREIGN KEY (FK_Pessoa_ID_pessoa)
    REFERENCES Pessoa (ID_pessoa)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Pessoa_funcionario ADD CONSTRAINT FK_Pessoa_funcionario_1
    FOREIGN KEY (FK_Pessoa_ID_pessoa)
    REFERENCES Pessoa (ID_pessoa)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Companhia ADD CONSTRAINT FK_Companhia_1
    FOREIGN KEY (FK_Empresa_ID_empresa)
    REFERENCES Empresa (ID_empresa)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Rodoviaria ADD CONSTRAINT FK_Rodoviaria_1
    FOREIGN KEY (FK_Empresa_ID_empresa)
    REFERENCES Empresa (ID_empresa)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Tem ADD CONSTRAINT FK_Tem_0
    FOREIGN KEY (FK_Pessoa_passageiro_ID_passageiro, FK_Pessoa_passageiro_FK_Pessoa_ID_pessoa)
    REFERENCES Pessoa_passageiro (ID_passageiro, FK_Pessoa_ID_pessoa)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE Tem ADD CONSTRAINT FK_Tem_1
    FOREIGN KEY (FK_Passagem_ID_passagem)
    REFERENCES Passagem (ID_passagem)
    ON DELETE RESTRICT ON UPDATE RESTRICT;


___________________________________________________
    
CREATE TABLE PESSOA
(
ID_PESSOA SERIAL PRIMARY KEY,
NOME varchar(5), 
CPF varchar(11),
TELEFONE varchar(15),
EMAIL varchar(50),
DATA_DE_NASCIMENTO Date, 
NACIONALIDADE varchar(50), 
);


CREATE TABLE PESSOA_PASSAGEIRO 
(
ID_PASSAGEIRO SERIAL PRIMARY KEY,
ID_PESSOA SERIAL,
ID_PASSAGEM SERIAL
);


CREATE TABLE PESSOA_FUNCIONARIO
(
ID_FUNCIONARIO SERIAL PRIMARY KEY,
ID_PESSOA SERIAL,
ID_EMPRESA SERIAL
);


CREATE TABLE EMPRESAS
(
ID_EMPRESA PRIMARY KEY,
NOME varchar(50), 
CLASSIFICACAO SERIAL
);


CREATE TABLE EMPRESA_COMPANHIA
(
ID_COMPANHIA PRIMARY KEY,
CLASSIFICACAO SERIAL
TELEFONE varchar(9),
EMAIL varchar(50)
);


CREATE TABLE EMPRESA_RODOVIARIA
(
ID_RODOVIARIA SERIAL PRIMARY KEY, 
CLASSIFICACAO SERIAL
ENDERECO varchar(10), 
HORARIO_DE_FUNCIONAMENTO Time
);



CREATE TABLE ROTAS
( 
ID_ROTA SERIAL PRIMARY KEY,
ID_COMPANHIA SERIAL, 
DESTINO varchar(50), 
HORA_SAIDA Time,
HORA_CHEGADA Time,
);


CREATE TABLE PASSAGEM
( 
ID_PASSAGEM SERIAL PRIMARY KEY, 
ID_ROTA SERIAL,
DATA_COMPRA Timestamp,
DATA_VIAGEM Timestamp,
PRECO Money
);




ALTER TABLE EMPRESAS ADD FOREIGN KEY(CLASSIFICACAO) REFERENCES EMPRESA_RODOVIARIA (CLASSIFICACAO);
ALTER TABLE EMPRESAS ADD FOREIGN KEY(CLASSIFICACAO) REFERENCES EMPRESA_COMPANHIA (CLASSIFICACAO);

ALTER TABLE ROTAS ADD FOREIGN KEY(ID_COMPANHIA) REFERENCES EMPRESA_COMPANHIA (ID_COMPANHIA);

ALTER TABLE PASSAGEM ADD FOREIGN KEY(ID_ROTA) REFERENCES ROTAS (ID_ROTA);

ALTER TABLE PESSOA_PASSAGEIRO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA (ID_PESSOA);
ALTER TABLE PESSOA_PASSAGEIRO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PASSAGEM (ID_PASSAGEM);

ALTER TABLE PESSOA_FUNCIONARIO ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA (ID_PESSOA);
ALTER TABLE PESSOA_FUNCIONARIO ADD FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA);

